# Generated by Django 3.2.9 on 2021-12-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211208_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
